server:
  port: 8080
langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASHSCOPE_API_KEY:}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3.7-plus
      timeout: 120s
      max-tokens: 2048
      temperature: 0.1
      stream-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  dashscope:
    embedding-model:
      api-key: ${DASHSCOPE_API_KEY:}
      model-name: text-embedding-v1
milvus:
  host: localhost
  port: 19530
  collection-name: investment_edu_v3  # 全新集合
elasticsearch:
  host: localhost
  port: 9200
  index-name: investment_edu_v3   # 全新索引

logging:
  level:
    dev.langchain4j: DEBUG
